---
- name: Install Patroni for this distribution
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Create Patroni config and log directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ patroni_user }}"
    group: "{{ patroni_group }}"
    mode: "0750"
  loop:
    - "{{ patroni_config_dir }}"
    - "{{ patroni_log_dir }}"
