---
- name: Install Patroni build dependencies
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-dev
      - python3-psycopg2
      - gcc
    state: present

- name: Install Patroni and kazoo from PyPI
  ansible.builtin.pip:
    name:
      - "{{ patroni_package }}"
      - "{{ patroni_kazoo_package }}"
    extra_args: --upgrade
    executable: pip3
